<?php
/**
 * Created by PhpStorm.
 * User: Owner
 * Date: 1/5/2017
 * Time: 2:12 PM
 */

namespace Acme\Repositories;


class StaffRepository extends Repository{

    protected $listener;

    public function setListener($listener){
        $this->listener = $listener;
    }


    public function model(){
        return 'App\Staff';
    }

    public function edit($id)
    {
        // TODO: Implement edit() method.
    }

    public function create()
    {
        // TODO: Implement create() method.
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function allStaffs(){
        return $this->model->all();
    }

    public function getFillable(){
        return $this->model->getFillable();
    }
    public function findStaff($id){
        return $this->model->find($id);
    }

    public function store(Array $input){
        $action = "create";
        $data = $this->model->create($input);
        //$this->listener->passed($action, $data->id);
        return $data;
    }

    public function update(array $input, $id)
    {
        $action = "edit";
        $this->model->where('id',$id)->update($input);
        //return $this->listener->passed($action, $id);
    }

    public function destroy($id){
        $action = "delete";
        $this->model->where('id',$id)->delete();
        //return $this->listener->passed($action, $id);
    }

}